### PR TITLE
Remove bad example in metal port get

### LINKED ISSUE #213: Remove bad example in metal port get
Example for metal port get should be removed as that functionality doesn't exist.

```sh
❯ metal port get
Error: required flag(s) "port-id" not set
Usage:
  metal port get -i <port_UUID> [flags]

Examples:
  # Retrieves list of the current user's ports:
  metal port get

  # Retrieves details of an port:
  metal port get -i 3bd5bf07-6094-48ad-bd03-d94e8712fdc8

Flags:
  -h, --help             help for get
  -i, --port-id string   The UUID of a port.

Global Flags:
      --config string        Path to JSON or YAML configuration file
      --exclude strings      Comma separated Href references to collapse in results, may be dotted three levels deep
      --filter stringArray   Filter 'get' actions with name value pairs. Filter is not supported by all resources and is implemented as request query parameters.
      --include strings      Comma separated Href references to expand in results, may be dotted three levels deep
  -o, --output string        Output format (*table, json, yaml)
      --search string        Search keyword for use in 'get' actions. Search is not supported by all resources.
      --sort-by string       Sort fields for use in 'get' actions. Sort is not supported by all resources.
      --sort-dir string      Sort field direction for use in 'get' actions. Sort is not supported by all resources.
      --token string         Metal API Token (METAL_AUTH_TOKEN)
```

### PR DESCRIPTION
**Pull request by cprivitere**
Fixes #213

Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>

### CODE REVIEW

File: internal/ports/retrieve.go [hunk 1]
```diff
@@ -36,10 +36,7 @@ func (c *Client) Retrieve() *cobra.Command {
 		Aliases: []string{},
 		Short:   "Retrieves the details of the specified port.",
 		Long:    "Retrieves the details of the specified port. Details of an port are only available to its members.",
-		Example: `  # Retrieves list of the current user's ports:
-  metal port get
-
-  # Retrieves details of an port:
+		Example: `  # Retrieves details of an port:
```
Comment (displague) [inline internal/ports/retrieve.go]:
```suggestion
		Example: `  # Retrieves the details of a port:
```
