### PR TITLE
fix: output for convert layer2 to layer 3 command

### LINKED ISSUE #386: converting from layer2 to layer3 bond with IPV4 and IPV6 shows some junk output
why port convert from layer2 to layer3 bond with IPV4 and IPV6 shows some Junk data

```
Vasubabus-MacBook-Pro:bin vasubabu$ ./metal port convert -i d414a2ca-2e91-4e2d-a598-42180c354e9d -2=false -b -4 -6
2023/11/07 23:29:57 Converting port d414a2ca-2e91-4e2d-a598-42180c354e9d to layer-3 with addresses [{0x140002c2540 0x140002c2544 map[]} {0x140002c2540 0x140002c2544 map[]} {0x140002c2540 0x140002c2544 map[]}]
```

_Originally posted by @vasubabu in https://github.com/equinix/metal-cli/pull/355#pullrequestreview-1718403693_

### PR DESCRIPTION
**Pull request by aayushrangwala**
metal-cli Convert subcommand from layer 2 to layer 3 logs pointers for the addresses

Fixes: https://github.com/equinix/metal-cli/issues/386 and https://github.com/equinix/metal-cli/issues/387

### CODE REVIEW

**Comment by aayushrangwala** [comment]
@displague @ctreatma Please trigger E2E tests

File: internal/ports/convert.go [hunk 1]
```diff
@@ -87,15 +90,20 @@ func (c *Client) Convert() *cobra.Command {
...
 				public = true
 				addrs = append(addrs, metal.PortConvertLayer3InputRequestIpsInner{AddressFamily: &addressFamily, Public: &public})
+
+				addressType = "public"
+				addressFamilyStrs = append(addressFamilyStrs, strconv.Itoa(int(metal.IPADDRESSADDRESSFAMILY__6)))
 			}
 
 			convToL3 := func(portID string) (*metal.Port, *http.Response, error) {
-				log.Printf("Converting port %s to layer-3 with addresses %v", portID, addrs)
+				log.Printf("Converting port %s to layer-3 with [%s] addresses IPv[%v]", portID, addressType, addressFamilyStrs)
```
Comment (displague) [inline internal/ports/convert.go]: addressType will be `public` when both public and private (required, will always be true when enabling layer3).

Was the intent to say (pseudo-code):
`"Converting port %s to layer-3 with private IPv4" (conditionally " and public " (conditionally join(IPv4AndOrIPv6, ", ")) " addresses")`

Comment (displague) [reply internal/ports/convert.go]: I don't think we offer this level of detail for anything else being created. We don't say, for example, "Creating a device in metro sv with plan c3.small.x86 and OS alpine"

I think we could omit this log message altogether if we really don't do it in the usual create or update case.
Perhaps a reason to keep it would be if the arguments to this command are so complicated that you never really know what to expect on the other end when you ask for something, but I think we have a handle on that now that we are addressing the bonding and converting actions not performing the actions that they logically should have.

Comment (aayushrangwala) [reply internal/ports/convert.go]: Got it. Fixed

**Review by displague — APPROVED** [review]
