### PR TITLE
fix: aligned the VRF table columns

### LINKED ISSUE #436: VRF Create output issue
### What happened?
When we create a vrf currently, we get the following output:

```
❯ metal vrf create  -m ch -r 192.168.1.1/29 -a 12003 -n testvrf
+---------+------+-------------+----------------+-------------------------------+---------+
|   ID    | NAME | DESCRIPTION |    LOCALASN    |           IPRANGES            | CREATED |
+---------+------+-------------+----------------+-------------------------------+---------+
| testvrf |      | 12003       | 192.168.1.0/29 | 2024-01-19 20:33:52 +0000 UTC |
+---------+------+-------------+----------------+-------------------------------+---------+
```

If you wait a sec and then run a get, you get something like this

```
+--------------------------------------+---------+-------------+----------------+----------+-------------------------------+
|                  ID                  |  NAME   | DESCRIPTION |    IPRANGES    | LOCALASN |            CREATED            |
+--------------------------------------+---------+-------------+----------------+----------+-------------------------------+
| 5ee64f98-fa3d-47f8-83c9-273dd7298147 | testvrf |             | 192.168.1.0/29 | 12003    | 2024-01-19 20:33:52 +0000 UTC |
+--------------------------------------+---------+-------------+----------------+----------+-------------------------------+
```
Ideally, the initial output should look more like the latter, at least putting fields in the right columns if we don't have all the info yet.

### How can we reproduce it?
Make a vrf with `metal vrf create`

CLI version (`metal --version`): 0.19.0

### PR DESCRIPTION
**Pull request by codinja1188**
Fixes #436

### CODE REVIEW

**Comment by codinja1188** [comment]
## Test Results:

```
Vasubabus-MacBook-Pro:bin vasubabu$ ./metal vrf create  -m ch -r 192.168.10.1/29 -a 12004 -n testvrf2
+--------------------------------------+----------+-------------+-----------------+----------+-------------------------------+
|                  ID                  |   NAME   | DESCRIPTION |    IPRANGES     | LOCALASN |            CREATED            |
+--------------------------------------+----------+-------------+-----------------+----------+-------------------------------+
| 4b7883b0-aa23-46dc-97c2-c75f24a21a4d | testvrf2 |             | 192.168.10.0/29 | 12004    | 2024-02-02 14:55:50 +0000 UTC |
+--------------------------------------+----------+-------------+-----------------+----------+-------------------------------+
Vasubabus-MacBook-Pro:bin vasubabu$ ./metal vrf get
+--------------------------------------+---------------+---------------+-----------------+----------+-------------------------------+
|                  ID                  |     NAME      |  DESCRIPTION  |    IPRANGES     | LOCALASN |            CREATED            |
+--------------------------------------+---------------+---------------+-----------------+----------+-------------------------------+
| c099c8ac-e013-4657-81aa-3be337cf4ad5 | cli-vrf-test5 | cli-vrf-test5 | 100.77.1.0/24   | 3171     | 2024-01-29 17:10:31 +0000 UTC |
| bb4f22d5-4ff7-4469-ab98-ce2680469fd5 | testvrf       |               | 192.168.1.0/29  | 12003    | 2024-02-02 14:52:03 +0000 UTC |
| 4b7883b0-aa23-46dc-97c2-c75f24a21a4d | testvrf2      |               | 192.168.10.0/29 | 12004    | 2024-02-02 14:55:50 +0000 UTC |
+--------------------------------------+---------------+---------------+-----------------+----------+-------------------------------+
```

File: internal/vrf/create.go [hunk 1]
```diff
@@ -51,8 +51,8 @@ func (c *Client) Create() *cobra.Command {
 			data := make([][]string, 1)
 
 			// This output block below is probably incorrect but leaving it for now for testing later.
```
Comment (displague) [inline internal/vrf/create.go]:
```suggestion
```

**Review by displague — APPROVED** [review]
